version: "2"
services:
  jenkins:
    restart: always
    image: diceone/rpi-jenkins:latest 
    ports:
      - 8080:8080
    volumes:
      - /mnt/archive/jenkins:/usr/local/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
